version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai-eval-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_eval
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-network

  postgres-test:
    image: postgres:15
    container_name: ai-eval-db-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_eval_test
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - ai-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama

    ports:
      - '11434:11434'

    volumes:
      - ollama_data:/root/.ollama

    restart: unless-stopped

  ollama-init:
    image: ollama/ollama:latest

    depends_on:
      - ollama

    entrypoint: >
      /bin/sh -c "
      sleep 5;
      ollama pull qwen2.5:7b;
      "

    environment:
      - OLLAMA_HOST=http://ollama:11434

volumes:
  postgres_data:
  postgres_test_data:
  ollama_data:

networks:
  ai-network:
