version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai_eval-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_eval
    ports:
      - '5432:5432'
    volumes:
      - ai_eval-data:/var/lib/postgresql/data
    networks:
      - ai-network

  postgres-test:
    image: postgres:15
    container_name: ai_eval-db-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_eval_test
    ports:
      - '5433:5432'
    volumes:
      - ai_eval-test-data:/var/lib/postgresql/data
    networks:
      - ai-network

volumes:
  ai_eval-data:
  ai_eval-test-data:

networks:
  ai-network: